[build]
  command = "npm run build"
  publish = "dist/reclutamiento-fae/browser"

[[plugins]]
  package = "@netlify/angular-runtime"

[[redirects]]
  from = "/"
  to = "/home"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.csr.html"
  status = 200
